# FILE: docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: uptime-monitor-web
    environment:
      - DATABASE_URL=sqlite:////data/uptime_monitor.db
      - SECRET_KEY=5298c840c107b7882dc4d6d9c8f2760d8b37eb81c34e3ff701d93d5004bf769c
    volumes:
      - db-data:/data
    ports:
      - "5001:5000"
    restart: unless-stopped

  monitor:
    build: .
    container_name: uptime-monitor-app
    environment:
      - DATABASE_URL=sqlite:////data/uptime_monitor.db
    volumes:
      - db-data:/data
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      - web
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: uptime-monitor-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: uptime-monitor-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  db-data:
